-- Manga Workflow PostgreSQL Schema v2
-- Clone-only improvement file. Original Context/Untitled.sql is preserved unchanged.
-- DBMS target: PostgreSQL 14+.

-- -----------------------------------------------------------------------------
-- Utility
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- Module A: Identity, roles, skills, boards, audit
-- -----------------------------------------------------------------------------

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  role VARCHAR(40) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  profile_image VARCHAR(500),
  bio TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_users_role CHECK (role IN ('admin', 'mangaka', 'assistant', 'tantou_editor', 'editorial_board_member')),
  CONSTRAINT ck_users_status CHECK (status IN ('active', 'inactive', 'suspended'))
);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE skills (
  skill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  created_by INTEGER NOT NULL REFERENCES users(user_id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_skills (
  user_skill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  skill_id INTEGER NOT NULL REFERENCES skills(skill_id) ON DELETE CASCADE,
  assigned_by INTEGER NOT NULL REFERENCES users(user_id),
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_skills_user_skill UNIQUE (user_id, skill_id)
);

CREATE TABLE editorial_boards (
  board_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_name VARCHAR(150) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_by INTEGER NOT NULL REFERENCES users(user_id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dissolved_at TIMESTAMP,
  CONSTRAINT ck_editorial_boards_status CHECK (status IN ('active', 'dissolved')),
  CONSTRAINT ck_editorial_boards_dissolved CHECK ((status = 'dissolved' AND dissolved_at IS NOT NULL) OR (status = 'active' AND dissolved_at IS NULL))
);

CREATE TABLE board_memberships (
  membership_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id INTEGER NOT NULL REFERENCES editorial_boards(board_id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE,
  CONSTRAINT ck_board_memberships_date CHECK (end_date IS NULL OR end_date >= start_date),
  CONSTRAINT uq_board_memberships_member_period UNIQUE (board_id, user_id, start_date)
);

CREATE TABLE audit_logs (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id INTEGER REFERENCES users(user_id),
  action VARCHAR(100) NOT NULL,
  target_type VARCHAR(80) NOT NULL,
  target_id INTEGER,
  details JSONB,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Module B: Series proposal, manuscript review, board voting
-- -----------------------------------------------------------------------------

CREATE TABLE series (
  series_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mangaka_id INTEGER NOT NULL REFERENCES users(user_id),
  editor_id INTEGER REFERENCES users(user_id),
  title VARCHAR(200) NOT NULL,
  genre VARCHAR(100),
  synopsis TEXT,
  target_audience VARCHAR(80),
  status VARCHAR(40) NOT NULL DEFAULT 'draft',
  publish_schedule VARCHAR(20),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cancelled_at TIMESTAMP,
  CONSTRAINT ck_series_status CHECK (status IN ('draft', 'submitted_to_editor', 'under_editor_review', 'needs_revision', 'escalated_to_board', 'approved', 'serializing', 'on_hold', 'cancelled', 'archived')),
  CONSTRAINT ck_series_schedule CHECK (publish_schedule IS NULL OR publish_schedule IN ('weekly', 'biweekly', 'monthly', 'irregular')),
  CONSTRAINT ck_series_cancelled CHECK ((status = 'cancelled' AND cancelled_at IS NOT NULL) OR status <> 'cancelled')
);

CREATE TRIGGER trg_series_updated_at
BEFORE UPDATE ON series
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE manuscripts (
  manuscript_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
  version INTEGER NOT NULL DEFAULT 1,
  file_path VARCHAR(500) NOT NULL,
  file_type VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  submitted_at TIMESTAMP,
  locked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_manuscripts_series_version UNIQUE (series_id, version),
  CONSTRAINT ck_manuscripts_version CHECK (version > 0),
  CONSTRAINT ck_manuscripts_status CHECK (status IN ('draft', 'submitted', 'under_review', 'needs_revision', 'approved_by_editor', 'escalated', 'archived')),
  CONSTRAINT ck_manuscripts_submit_lock CHECK ((status = 'draft' AND submitted_at IS NULL AND locked = FALSE) OR status <> 'draft')
);

CREATE TABLE editor_annotations (
  annotation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manuscript_id INTEGER NOT NULL REFERENCES manuscripts(manuscript_id) ON DELETE CASCADE,
  editor_id INTEGER NOT NULL REFERENCES users(user_id),
  page_number INTEGER NOT NULL,
  x NUMERIC(6,3) NOT NULL,
  y NUMERIC(6,3) NOT NULL,
  annotation_type VARCHAR(30) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_editor_annotations_page CHECK (page_number > 0),
  CONSTRAINT ck_editor_annotations_coordinates CHECK (x >= 0 AND x <= 100 AND y >= 0 AND y <= 100),
  CONSTRAINT ck_editor_annotations_type CHECK (annotation_type IN ('content', 'dialogue', 'artwork', 'layout', 'continuity', 'other'))
);

CREATE TABLE submissions (
  submission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
  manuscript_id INTEGER NOT NULL REFERENCES manuscripts(manuscript_id),
  editor_id INTEGER NOT NULL REFERENCES users(user_id),
  board_id INTEGER NOT NULL REFERENCES editorial_boards(board_id),
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  editor_report TEXT,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at TIMESTAMP,
  CONSTRAINT ck_submissions_status CHECK (status IN ('pending', 'voting_open', 'approved', 'rejected', 'closed')),
  CONSTRAINT ck_submissions_decided_at CHECK ((status IN ('approved', 'rejected', 'closed') AND decided_at IS NOT NULL) OR status IN ('pending', 'voting_open'))
);

CREATE TABLE submission_votes (
  vote_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id INTEGER NOT NULL REFERENCES submissions(submission_id) ON DELETE CASCADE,
  voter_id INTEGER NOT NULL REFERENCES users(user_id),
  vote VARCHAR(10) NOT NULL,
  comment TEXT,
  voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_submission_votes_submission_voter UNIQUE (submission_id, voter_id),
  CONSTRAINT ck_submission_votes_vote CHECK (vote IN ('approve', 'reject', 'abstain'))
);

-- -----------------------------------------------------------------------------
-- Module C: Chapter production, pages, regions, tasks, reviews
-- -----------------------------------------------------------------------------

CREATE TABLE chapters (
  chapter_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
  chapter_number INTEGER NOT NULL,
  title VARCHAR(200),
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  deadline TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_chapters_series_number UNIQUE (series_id, chapter_number),
  CONSTRAINT ck_chapters_number CHECK (chapter_number > 0),
  CONSTRAINT ck_chapters_status CHECK (status IN ('draft', 'in_progress', 'pages_uploaded', 'tasks_in_progress', 'ready_for_editor', 'published', 'cancelled'))
);

CREATE TRIGGER trg_chapters_updated_at
BEFORE UPDATE ON chapters
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE pages (
  page_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id INTEGER NOT NULL REFERENCES chapters(chapter_id) ON DELETE CASCADE,
  page_number INTEGER NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  width_px INTEGER,
  height_px INTEGER,
  status VARCHAR(30) NOT NULL DEFAULT 'uploaded',
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_pages_chapter_number UNIQUE (chapter_id, page_number),
  CONSTRAINT ck_pages_number CHECK (page_number > 0),
  CONSTRAINT ck_pages_dimensions CHECK ((width_px IS NULL OR width_px > 0) AND (height_px IS NULL OR height_px > 0)),
  CONSTRAINT ck_pages_status CHECK (status IN ('uploaded', 'segmented', 'tasks_assigned', 'tasks_in_progress', 'all_tasks_approved', 'finalized'))
);

CREATE TABLE page_regions (
  region_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES pages(page_id) ON DELETE CASCADE,
  region_type VARCHAR(30) NOT NULL,
  x NUMERIC(6,3) NOT NULL,
  y NUMERIC(6,3) NOT NULL,
  width_pct NUMERIC(6,3) NOT NULL,
  height_pct NUMERIC(6,3) NOT NULL,
  polygon_points JSONB,
  ai_generated BOOLEAN NOT NULL DEFAULT FALSE,
  ai_confidence NUMERIC(5,4),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_page_regions_type CHECK (region_type IN ('panel', 'speech_bubble', 'character', 'background', 'effect_line', 'other')),
  CONSTRAINT ck_page_regions_bounds CHECK (x >= 0 AND x <= 100 AND y >= 0 AND y <= 100 AND width_pct > 0 AND width_pct <= 100 AND height_pct > 0 AND height_pct <= 100 AND x + width_pct <= 100 AND y + height_pct <= 100),
  CONSTRAINT ck_page_regions_ai_confidence CHECK (ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1))
);

CREATE TABLE page_versions (
  page_version_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES pages(page_id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  source_type VARCHAR(30) NOT NULL,
  created_by INTEGER REFERENCES users(user_id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_page_versions_page_version UNIQUE (page_id, version),
  CONSTRAINT ck_page_versions_version CHECK (version > 0),
  CONSTRAINT ck_page_versions_source_type CHECK (source_type IN ('original', 'assistant_output', 'compiled', 'final'))
);

CREATE TABLE tasks (
  task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id INTEGER NOT NULL REFERENCES page_regions(region_id) ON DELETE CASCADE,
  assigned_to INTEGER NOT NULL REFERENCES users(user_id),
  assigned_by INTEGER NOT NULL REFERENCES users(user_id),
  task_type VARCHAR(30) NOT NULL,
  instructions TEXT,
  reference_files JSONB,
  unit_count NUMERIC(8,2) NOT NULL DEFAULT 1,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  deadline TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_tasks_type CHECK (task_type IN ('background', 'inking', 'shading', 'screentone', 'effect_line', 'speech_bubble', 'cleanup', 'coloring', 'other')),
  CONSTRAINT ck_tasks_unit_count CHECK (unit_count > 0),
  CONSTRAINT ck_tasks_status CHECK (status IN ('pending', 'in_progress', 'submitted', 'approved', 'rejected', 'redo_requested', 'cancelled'))
);

CREATE TRIGGER trg_tasks_updated_at
BEFORE UPDATE ON tasks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE task_submissions (
  submission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id INTEGER NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
  assistant_id INTEGER NOT NULL REFERENCES users(user_id),
  version INTEGER NOT NULL DEFAULT 1,
  file_path VARCHAR(500) NOT NULL,
  notes TEXT,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_task_submissions_task_version UNIQUE (task_id, version),
  CONSTRAINT ck_task_submissions_version CHECK (version > 0)
);

CREATE TABLE task_reviews (
  review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_submission_id INTEGER NOT NULL REFERENCES task_submissions(submission_id) ON DELETE CASCADE,
  reviewer_id INTEGER NOT NULL REFERENCES users(user_id),
  decision VARCHAR(20) NOT NULL,
  feedback TEXT,
  feedback_annotations JSONB,
  reviewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_task_reviews_submission UNIQUE (task_submission_id),
  CONSTRAINT ck_task_reviews_decision CHECK (decision IN ('approved', 'rejected', 'redo_requested')),
  CONSTRAINT ck_task_reviews_feedback_required CHECK (decision = 'approved' OR feedback IS NOT NULL)
);

-- -----------------------------------------------------------------------------
-- Module D: Reader data, ranking, decisions, notifications, earnings
-- -----------------------------------------------------------------------------

CREATE TABLE reader_poll_data (
  poll_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
  entered_by INTEGER NOT NULL REFERENCES users(user_id),
  publication_cycle VARCHAR(50) NOT NULL,
  reader_votes INTEGER NOT NULL DEFAULT 0,
  likes INTEGER NOT NULL DEFAULT 0,
  shares INTEGER NOT NULL DEFAULT 0,
  sales_units INTEGER NOT NULL DEFAULT 0,
  composite_score NUMERIC(14,4) NOT NULL DEFAULT 0,
  entered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_reader_poll_data_series_cycle UNIQUE (series_id, publication_cycle),
  CONSTRAINT ck_reader_poll_data_non_negative CHECK (reader_votes >= 0 AND likes >= 0 AND shares >= 0 AND sales_units >= 0 AND composite_score >= 0),
  CONSTRAINT ck_reader_poll_data_cycle CHECK (publication_cycle ~ '^([0-9]{4}-W[0-9]{2}|[0-9]{4}-[0-9]{2})$')
);

CREATE TABLE series_rankings (
  ranking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
  poll_id INTEGER NOT NULL REFERENCES reader_poll_data(poll_id) ON DELETE CASCADE,
  publication_cycle VARCHAR(50) NOT NULL,
  rank_position INTEGER NOT NULL,
  composite_score NUMERIC(14,4) NOT NULL,
  rank_change INTEGER,
  ranked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_series_rankings_series_cycle UNIQUE (series_id, publication_cycle),
  CONSTRAINT uq_series_rankings_cycle_position UNIQUE (publication_cycle, rank_position),
  CONSTRAINT ck_series_rankings_position CHECK (rank_position > 0),
  CONSTRAINT ck_series_rankings_score CHECK (composite_score >= 0),
  CONSTRAINT ck_series_rankings_cycle CHECK (publication_cycle ~ '^([0-9]{4}-W[0-9]{2}|[0-9]{4}-[0-9]{2})$')
);

CREATE TABLE series_decisions (
  decision_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
  board_id INTEGER NOT NULL REFERENCES editorial_boards(board_id),
  decided_by INTEGER NOT NULL REFERENCES users(user_id),
  decision VARCHAR(20) NOT NULL,
  new_schedule VARCHAR(20),
  rationale TEXT NOT NULL,
  decided_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  effective_from DATE,
  CONSTRAINT ck_series_decisions_decision CHECK (decision IN ('maintain', 'reschedule', 'cancel', 'change_format')),
  CONSTRAINT ck_series_decisions_schedule CHECK (new_schedule IS NULL OR new_schedule IN ('weekly', 'biweekly', 'monthly', 'irregular')),
  CONSTRAINT ck_series_decisions_reschedule CHECK ((decision = 'reschedule' AND new_schedule IS NOT NULL AND effective_from IS NOT NULL) OR decision <> 'reschedule'),
  CONSTRAINT ck_series_decisions_cancel CHECK ((decision = 'cancel' AND effective_from IS NOT NULL) OR decision <> 'cancel')
);

CREATE TABLE series_decision_votes (
  vote_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id INTEGER NOT NULL REFERENCES series_decisions(decision_id) ON DELETE CASCADE,
  voter_id INTEGER NOT NULL REFERENCES users(user_id),
  vote VARCHAR(20) NOT NULL,
  comment TEXT,
  voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_series_decision_votes_decision_voter UNIQUE (decision_id, voter_id),
  CONSTRAINT ck_series_decision_votes_vote CHECK (vote IN ('maintain', 'reschedule', 'cancel', 'change_format', 'abstain'))
);

CREATE TABLE notifications (
  notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  trigger_event VARCHAR(40) NOT NULL,
  related_entity_type VARCHAR(80),
  related_entity_id INTEGER,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_notifications_trigger CHECK (trigger_event IN ('series_submitted', 'revision_requested', 'series_escalated', 'series_approved', 'series_rejected', 'task_assigned', 'task_submitted', 'task_approved', 'task_redo_requested', 'ranking_updated', 'low_rank_warning', 'series_rescheduled', 'series_cancelled'))
);

CREATE TABLE earning_rates (
  rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type VARCHAR(30) NOT NULL,
  rate_per_page NUMERIC(10,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  effective_from DATE NOT NULL,
  effective_to DATE,
  set_by INTEGER NOT NULL REFERENCES users(user_id),
  CONSTRAINT ck_earning_rates_task_type CHECK (task_type IN ('background', 'inking', 'shading', 'screentone', 'effect_line', 'speech_bubble', 'cleanup', 'coloring', 'other')),
  CONSTRAINT ck_earning_rates_amount CHECK (rate_per_page >= 0),
  CONSTRAINT ck_earning_rates_dates CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE UNIQUE INDEX uq_earning_rates_active_task_type
ON earning_rates(task_type)
WHERE effective_to IS NULL;

-- -----------------------------------------------------------------------------
-- Indexes for common screens and workflow checks
-- -----------------------------------------------------------------------------

CREATE INDEX ix_users_role_status ON users(role, status);
CREATE INDEX ix_user_skills_user ON user_skills(user_id);
CREATE INDEX ix_board_memberships_board_active ON board_memberships(board_id, end_date);
CREATE INDEX ix_audit_logs_target ON audit_logs(target_type, target_id, occurred_at DESC);
CREATE INDEX ix_audit_logs_actor ON audit_logs(actor_id, occurred_at DESC);

CREATE INDEX ix_series_mangaka_status ON series(mangaka_id, status);
CREATE INDEX ix_series_editor_status ON series(editor_id, status);
CREATE INDEX ix_series_status ON series(status);
CREATE INDEX ix_manuscripts_series_status ON manuscripts(series_id, status);
CREATE INDEX ix_editor_annotations_manuscript ON editor_annotations(manuscript_id, resolved);
CREATE INDEX ix_submissions_board_status ON submissions(board_id, status);
CREATE INDEX ix_submission_votes_submission ON submission_votes(submission_id);

CREATE INDEX ix_chapters_series_status ON chapters(series_id, status);
CREATE INDEX ix_pages_chapter_status ON pages(chapter_id, status);
CREATE INDEX ix_page_regions_page ON page_regions(page_id);
CREATE INDEX ix_page_versions_page ON page_versions(page_id, version DESC);
CREATE INDEX ix_tasks_assigned_status ON tasks(assigned_to, status);
CREATE INDEX ix_tasks_region_status ON tasks(region_id, status);
CREATE INDEX ix_task_submissions_task ON task_submissions(task_id, version DESC);
CREATE INDEX ix_task_reviews_reviewer ON task_reviews(reviewer_id, reviewed_at DESC);

CREATE INDEX ix_reader_poll_data_cycle ON reader_poll_data(publication_cycle);
CREATE INDEX ix_series_rankings_cycle_position ON series_rankings(publication_cycle, rank_position);
CREATE INDEX ix_series_decisions_series ON series_decisions(series_id, decided_at DESC);
CREATE INDEX ix_notifications_recipient_read_created ON notifications(recipient_id, is_read, created_at DESC);

-- -----------------------------------------------------------------------------
-- Notes for implementation
-- -----------------------------------------------------------------------------

COMMENT ON TABLE users IS 'Canonical fixed-role user table. Dynamic RBAC is out of MVP.';
COMMENT ON TABLE manuscripts IS 'Manuscript submitted for proposal workflow, distinct from chapter production pages.';
COMMENT ON TABLE submissions IS 'Proposal submission from Tantou Editor to Editorial Board.';
COMMENT ON TABLE task_submissions IS 'Assistant work submission for production task, distinct from proposal submission.';
COMMENT ON TABLE page_versions IS 'Stores original/assistant/compiled/final file references; MVP does not require automatic image merging.';
COMMENT ON TABLE series_decision_votes IS 'Optional member-level voting for active-series decisions. Can remain unused if meeting outcome only is implemented.';
COMMENT ON TABLE earning_rates IS 'Display-only earning estimation rates; no payment transaction is modeled.';

-- End of schema_postgresql_v2.sql
