server.port=8080
spring.application.name=manga-workflow-api
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
